Ported transport protocol params from sdntrace_cp
kytos-ng/sdntrace pull request #92
Opened 2024-08-02 20:18 UTC by Ktmi

Closes #90
### Summary

Made it so that transport protocol params should be usable from the web UI. It should now be possible to set the source and destination port of a given packet.

### Local Tests

Can't test due to issue #91.

2024-08-05 14:51 UTC, viniarck requested changes
Overall looks good. 

It needs be locally tested though. cc'ing @Alopalao as a reviewer too, since he implemented that part in the back-end. 

<s>I'm requesting changes to update the changelog.</s>

I've tried out one simple example setting nw_proto and tp_src, and I've also managed to take the opportunity to confirm on wire the packet out:

![20240805_114558](https://github.com/user-attachments/assets/fba3add6-745e-42b4-bafc-5d5e2ade2995)

![20240805_115012](https://github.com/user-attachments/assets/26ad9535-db9d-4a43-83d7-97bc9cfe279e)

2024-08-05 14:54 UTC, viniarck approved these changes
Changelog doesn't need to be updated for this case (the feature is being released in the same version and we already got a generic UI line there), so I'm updating my review again. Once it's been locally tested (in addition to the simple example I helped out with), it can get merged. Great PR.

2024-08-05 15:35 UTC, Alopalao approved these changes
Looks good to me.

2024-08-08 19:20 UTC, Ktmi commented
Can confirm this works. I even captured the packets as they passed through the network.
![image](https://github.com/user-attachments/assets/7b37d63d-e45c-4db4-9c0e-c9064477eb70)

2024-08-08 19:21 UTC, merged